import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import './Login.css';

export default function Login() {
  const { user, signIn } = useAuth(); const navigate = useNavigate();
  const [form,setForm]=useState({email:'',password:''}),[showPassword,setShowPassword]=useState(false),[remember,setRemember]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  if(user)return <Navigate to="/app" replace/>;
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{await signIn(form.email,form.password,remember);navigate('/app',{replace:true})}catch(requestError){setError(requestError.response?.data?.message||'Unable to log in')}finally{setBusy(false)}};
  return <main className="login-page"><section className="login-intro"><div className="login-intro-top"><Link className="login-brand" to="/"><img src="/mail-software-advice-logo.png" alt=""/><span>Mail Software Advice</span></Link><Link className="back-home" to="/">← Back to home</Link></div><div className="login-message"><p className="login-eyebrow">Focused lead outreach</p><p>Import your lead files or connect Apollo, optionally verify prospects with AI, and manage outreach in one focused workspace.</p><ul><li>Import CSV or Excel</li><li>Discover and enrich leads with Apollo</li><li>AI verify and qualify leads (optional)</li><li>Manage personalized outreach with Resend</li></ul></div><small>Lead generation and outreach, simplified.</small></section><section className="login-panel"><div className="mobile-login-top"><Link className="login-brand dark" to="/"><img src="/mail-software-advice-logo.png" alt=""/><span>Mail Software Advice</span></Link><Link to="/">Home</Link></div><form className="login-form" onSubmit={submit}><p className="login-eyebrow">Secure access</p><h2>Welcome back</h2><p className="form-intro">Sign in to continue to Mail Software Advice.</p>{error&&<div className="login-error" role="alert">{error}</div>}<label>Email<input type="email" required autoFocus autoComplete="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} placeholder="you@example.com"/></label><label>Password<div className="password-field"><input type={showPassword?'text':'password'} required minLength="8" autoComplete="current-password" value={form.password} onChange={event=>setForm({...form,password:event.target.value})} placeholder="Enter your password"/><button type="button" onClick={()=>setShowPassword(value=>!value)}>{showPassword?'Hide':'Show'}</button></div></label><label className="remember"><input type="checkbox" checked={remember} onChange={event=>setRemember(event.target.checked)}/> Remember me</label><button className="login-submit" type="submit" disabled={busy}>{busy?'Logging in...':'Login'}</button><small className="login-note">Access is managed by your administrator. Public registration is not available.</small></form></section></main>;
}
