import { Link } from 'react-router-dom';
import './Documentation.css';

const flow = ['Import leads manually or from Apollo', 'Review subscribed leads', 'Optionally verify with AI', 'Select a Resend template', 'Preview and confirm', 'Send and track results'];

export default function Documentation() {
  return <div className="docs-page">
    <header className="docs-hero"><div><p className="docs-kicker">Mail Software Advice</p><h1>Application documentation</h1><p>Everything an administrator needs to configure the workspace and run a safe outreach campaign.</p></div><Link to="/app/settings">Open settings</Link></header>
    <nav className="docs-nav" aria-label="Documentation sections"><a href="#workflow">Workflow</a><a href="#leads">Leads</a><a href="#resend">Resend</a><a href="#ai">AI verification</a><a href="#campaigns">Campaigns</a><a href="#production">Production</a></nav>
    <main className="docs-content">
      <section id="workflow"><span className="section-number">01</span><div><h2>Core workflow</h2><p>The application follows one focused process from lead source to tracked outreach.</p><ol className="flow-list">{flow.map((item,index)=><li key={item}><b>{index+1}</b><span>{item}</span></li>)}</ol></div></section>
      <section id="leads"><span className="section-number">02</span><div><h2>Lead management</h2><p>Leads come from two user-facing sources: <strong>Manual Import</strong> and <strong>Apollo</strong>. CSV, Excel, API, and manually created records are grouped under Manual Import.</p><div className="docs-grid"><article><h3>Subscribed</h3><p>Eligible for campaign selection and sending.</p></article><article><h3>Unsubscribed</h3><p>Automatically excluded from every campaign. Administrators can also update this status manually.</p></article></div><p>Edit and delete controls are available in the final column of the Leads table. Imports prevent duplicate email addresses.</p></div></section>
      <section id="resend"><span className="section-number">03</span><div><h2>Resend email delivery</h2><p>Configure the Resend API key in Settings. Sender and reply-to details are managed directly by each published Resend template.</p><p>Templates used by this application receive exactly two variables:</p><pre><code>{'{{{name}}}\n{{{company_name}}}'}</code></pre><div className="docs-note"><strong>Lead mapping:</strong> <code>name</code> comes from the imported lead name, and <code>company_name</code> comes from the imported company.</div></div></section>
      <section id="ai"><span className="section-number">04</span><div><h2>AI verification</h2><p>AI verification is optional. Settings supports either OpenAI or Google Gemini. Select a provider, enter its API key and model, then use Save &amp; Test to verify the connection.</p><p>Campaigns remain sendable when AI verification is skipped.</p></div></section>
      <section id="campaigns"><span className="section-number">05</span><div><h2>Campaigns</h2><p>Choose saved leads, review recipients, optionally verify, select one of the configured Resend templates, and confirm before sending. Unsubscribed leads are excluded by the backend even if an older campaign still references them.</p><p>Use <strong>Reuse campaign</strong> from the campaign list to create a new campaign with the previous lead selection and template. The original campaign and its activity remain unchanged.</p></div></section>
      <section id="production"><span className="section-number">06</span><div><h2>Production configuration</h2><p>Configure secrets in the server environment rather than committing them to Git.</p><div className="env-list"><code>NODE_ENV=production</code><code>APP_URL=https://your-domain.com</code><code>DB_HOST / DB_NAME / DB_USER / DB_PASSWORD</code><code>AUTH_SECRET=a-long-random-secret</code></div><p><code>APP_URL</code> ensures email unsubscribe links use the public HTTPS domain. Run <code>npm run db:migrate</code> followed by <code>npm run db:sync</code> during deployment, then start the app with <code>npm start</code>.</p></div></section>
    </main>
  </div>;
}
