import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowBackRounded, CheckCircleRounded, CloudUploadRounded, DeleteOutlineRounded, DescriptionRounded, DownloadRounded } from '@mui/icons-material';
import { Alert, Box, Button, Card, CardContent, Chip, FormControl, Grid, LinearProgress, MenuItem, Select, Stack, Step, StepLabel, Stepper, ToggleButton, ToggleButtonGroup, Typography } from '@mui/material';
import { DataGrid } from '@mui/x-data-grid';
import * as importApi from '../../services/imports';

const targets = [['','Ignore column'],['name','Name'],['first_name','First name'],['last_name','Last name'],['job_title','Job title'],['company','Company'],['email','Email'],['linkedin_url','LinkedIn URL'],['phone','Phone'],['country','Country'],['company_size','Company size'],['industry','Industry'],['company_website','Website']];
const chipColor = { VALID:'success', INCOMPLETE:'info', DUPLICATE:'warning', 'INVALID EMAIL':'error', 'MISSING EMAIL':'error' };
const statusLabel = { VALID:'Valid', INCOMPLETE:'Incomplete', DUPLICATE:'Duplicate', 'INVALID EMAIL':'Invalid', 'MISSING EMAIL':'Invalid' };
const steps = ['Choose file','Map & validate','Review & import'];
const decorate = rows => rows.map(row => row.import_status === 'VALID' && (!row.name || !row.company || !row.job_title || !row.linkedin_url) ? { ...row, import_status:'INCOMPLETE', validation_reason:'Optional information is missing' } : row);
const allowed = file => /\.(csv|xlsx)$/i.test(file?.name || '');

export default function ImportLeads() {
  const inputRef=useRef(); const [active,setActive]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [file,setFile]=useState(null),[dragging,setDragging]=useState(false),[preview,setPreview]=useState(null),[rows,setRows]=useState([]),[selected,setSelected]=useState([]),[filter,setFilter]=useState('ALL'),[summary,setSummary]=useState(null),[history,setHistory]=useState([]);
  const loadHistory=()=>importApi.getImports().then(r=>setHistory(r.data)).catch(()=>{}); useEffect(() => { loadHistory(); }, []);
  const choose = candidate => { setError(''); if(!candidate)return; if(!allowed(candidate)){setError('Only .xlsx and .csv files are supported.');return} if(candidate.size>10*1024*1024){setError('File must be 10 MB or smaller.');return} setFile(candidate); };
  const upload=async()=>{setBusy(true);setError('');try{const response=await importApi.previewImport(file);const decorated=decorate(response.data.rows);setPreview(response.data);setRows(decorated);setSelected(decorated.filter(x=>['VALID','INCOMPLETE'].includes(x.import_status)).map(x=>x.row_number));setActive(1)}catch(err){setError(err.response?.data?.message||'Unable to read this file')}finally{setBusy(false)}};
  const changeMap=async(column,target)=>{const mapping={...preview.mapping,[column]:target};setPreview({...preview,mapping});setBusy(true);try{const response=await importApi.remapImport(preview.rawRows,mapping);const decorated=decorate(response.data);setRows(decorated);setSelected(decorated.filter(x=>['VALID','INCOMPLETE'].includes(x.import_status)).map(x=>x.row_number))}catch(err){setError(err.response?.data?.message||'Unable to apply mapping')}finally{setBusy(false)}};
  const confirm=async()=>{setBusy(true);setError('');try{const chosen=new Set(selected);const payloadRows=rows.map(row=>({...row,import_status:row.import_status==='INCOMPLETE'?'VALID':row.import_status,skip:['VALID','INCOMPLETE'].includes(row.import_status)&&!chosen.has(row.row_number)}));const response=await importApi.confirmImport({filename:preview.filename,source:preview.source,rows:payloadRows});setSummary(response.data);setActive(2);loadHistory()}catch(err){setError(err.response?.data?.message||'Unable to import leads')}finally{setBusy(false)}};
  const reset=()=>{setActive(0);setFile(null);setPreview(null);setRows([]);setSelected([]);setSummary(null);setError('');};
  const counts=useMemo(()=>rows.reduce((all,row)=>{const key=['INVALID EMAIL','MISSING EMAIL'].includes(row.import_status)?'INVALID':row.import_status;all[key]=(all[key]||0)+1;return all},{}),[rows]);
  const shown=useMemo(()=>filter==='ALL'?rows:filter==='INVALID'?rows.filter(r=>['INVALID EMAIL','MISSING EMAIL'].includes(r.import_status)):rows.filter(r=>r.import_status===filter),[rows,filter]);
  const previewCols=[{field:'import_status',headerName:'Status',width:120,renderCell:p=><Chip label={statusLabel[p.value]} color={chipColor[p.value]} size="small"/>},{field:'name',headerName:'Name',width:165},{field:'job_title',headerName:'Job title',width:155},{field:'company',headerName:'Company',width:180},{field:'email',headerName:'Email',width:225},{field:'linkedin_url',headerName:'LinkedIn',width:180,renderCell:p=>p.value?<Typography component="a" href={p.value} target="_blank" variant="body2" color="primary">View profile</Typography>:'—'},{field:'ai_verification',headerName:'AI verification',width:150,valueGetter:()=> 'Not requested'},{field:'qualification',headerName:'Qualification',width:135,valueGetter:(_,row)=>row.import_status==='VALID'?'Ready':'Review'},{field:'validation_reason',headerName:'Reason',width:220,valueGetter:(_,row)=>row.validation_reason||({'DUPLICATE':'Email already exists','INVALID EMAIL':'Invalid email format','MISSING EMAIL':'Email is required'}[row.import_status]||'Ready to import')}];
  const historyCols=[{field:'filename',headerName:'Filename',flex:1,minWidth:190},{field:'source',headerName:'Type',width:90},{field:'created_time',headerName:'Date',width:170,valueFormatter:v=>new Date(v).toLocaleString()},{field:'total_rows',headerName:'Rows',width:75},{field:'imported',headerName:'Imported',width:95},{field:'duplicates',headerName:'Duplicates',width:100},{field:'status',headerName:'Status',width:105,renderCell:p=><Chip label={p.value} size="small" color="success" variant="outlined"/>}];
  return <><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" spacing={2}><Box><Typography variant="h4">Import Leads</Typography><Typography color="text.secondary" mt={.5}>Upload an Excel or CSV file containing your prospects.</Typography></Box><Button component="a" href="/samples/leads-import-sample.csv" download startIcon={<DownloadRounded/>}>Download Sample CSV</Button></Stack>
    <Stepper activeStep={active} sx={{my:4}}>{steps.map(label=><Step key={label}><StepLabel>{label}</StepLabel></Step>)}</Stepper>{error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError('')}>{error}</Alert>}{busy&&<LinearProgress sx={{mb:2}}/>}
    {active===0&&<Card><CardContent sx={{p:{xs:2.5,sm:4}}}><Box onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);choose(e.dataTransfer.files[0])}} onClick={()=>!file&&inputRef.current?.click()} sx={{minHeight:285,border:'2px dashed',borderColor:dragging?'primary.main':file?'secondary.main':'#CACCDD',borderRadius:4,bgcolor:dragging?'#F0EFFF':file?'#F4FBF9':'#FAFAFC',display:'grid',placeItems:'center',textAlign:'center',p:4,cursor:file?'default':'pointer',transition:'.2s'}}><input ref={inputRef} hidden type="file" accept=".csv,.xlsx" onChange={e=>choose(e.target.files[0])}/>{file?<Stack alignItems="center" spacing={1.4}><Box sx={{width:64,height:64,borderRadius:3,display:'grid',placeItems:'center',bgcolor:'white',color:'secondary.main',boxShadow:'0 8px 24px rgba(30,80,70,.1)'}}><DescriptionRounded sx={{fontSize:34}}/></Box><Typography variant="h6">{file.name}</Typography><Stack direction="row" spacing={1}><Chip label={file.name.split('.').pop().toUpperCase()} size="small"/><Chip label={`${(file.size/1024).toFixed(1)} KB`} size="small" variant="outlined"/></Stack><Button color="error" size="small" startIcon={<DeleteOutlineRounded/>} onClick={e=>{e.stopPropagation();setFile(null);if(inputRef.current)inputRef.current.value=''}}>Remove file</Button></Stack>:<Stack alignItems="center" spacing={1.5}><Box sx={{width:68,height:68,borderRadius:'50%',display:'grid',placeItems:'center',bgcolor:'#EFEEFF',color:'primary.main'}}><CloudUploadRounded sx={{fontSize:36}}/></Box><Typography variant="h5">Drop your file here</Typography><Typography color="text.secondary">or</Typography><Button variant="outlined" onClick={e=>{e.stopPropagation();inputRef.current?.click()}}>Choose File</Button><Typography variant="caption" color="text.secondary">Supported: .xlsx, .csv · Maximum 10 MB</Typography></Stack>}</Box><Stack direction="row" justifyContent="flex-end" mt={3}><Button variant="contained" size="large" disabled={!file||busy} onClick={upload}>Continue</Button></Stack></CardContent></Card>}
    {active===1&&preview&&<><Card sx={{mb:3}}><CardContent sx={{p:3}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" alignItems={{md:'center'}} spacing={2}><Box><Typography variant="h6">Map spreadsheet columns</Typography><Typography color="text.secondary" variant="body2">Confirm how each column should be imported. Unneeded columns can be ignored.</Typography></Box><Chip icon={<DescriptionRounded/>} label={`${preview.filename} · ${rows.length} records`} variant="outlined"/></Stack><Grid container spacing={2} mt={1}>{preview.columns.map(column=><Grid size={{xs:12,sm:6,md:4}} key={column}><Typography variant="caption" color="text.secondary" fontWeight={700}>{column}</Typography><FormControl fullWidth size="small" sx={{mt:.5}}><Select value={preview.mapping[column]||''} onChange={e=>changeMap(column,e.target.value)}>{targets.map(([value,label])=><MenuItem value={value} key={value}>{label}</MenuItem>)}</Select></FormControl></Grid>)}</Grid></CardContent></Card><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" alignItems={{md:'center'}} spacing={2} mb={2}><ToggleButtonGroup exclusive size="small" value={filter} onChange={(_,value)=>value&&setFilter(value)} sx={{flexWrap:'wrap'}}>{[['ALL','All'],['VALID','Valid'],['INCOMPLETE','Incomplete'],['DUPLICATE','Duplicates'],['INVALID','Invalid']].map(([value,label])=><ToggleButton key={value} value={value}>{label} ({value==='ALL'?rows.length:(counts[value]||0)})</ToggleButton>)}</ToggleButtonGroup><Typography variant="body2" color="text.secondary"><strong>{selected.length}</strong> selected for import</Typography></Stack><Box sx={{height:480,bgcolor:'white',borderRadius:3}}><DataGrid rows={shown} columns={previewCols} getRowId={r=>r.row_number} checkboxSelection rowSelectionModel={selected} onRowSelectionModelChange={setSelected} isRowSelectable={p=>['VALID','INCOMPLETE'].includes(p.row.import_status)} loading={busy} disableRowSelectionOnClick/></Box><Card sx={{mt:2}}><CardContent><Grid container spacing={2}>{[['Total records',rows.length],['Valid',counts.VALID||0],['Incomplete',counts.INCOMPLETE||0],['Duplicates',counts.DUPLICATE||0],['Invalid',counts.INVALID||0],['Selected for import',selected.length]].map(([label,value])=><Grid size={{xs:6,sm:4,md:2}} key={label}><Typography variant="h6">{value}</Typography><Typography variant="caption" color="text.secondary">{label}</Typography></Grid>)}</Grid></CardContent></Card><Stack direction="row" justifyContent="space-between" mt={2}><Button startIcon={<ArrowBackRounded/>} onClick={reset}>Cancel</Button><Stack direction="row" spacing={1}><Button onClick={()=>setActive(0)}>Back</Button><Button variant="contained" onClick={confirm} disabled={busy||selected.length===0}>Import Leads</Button></Stack></Stack></>}
    {active===2&&summary&&<Card><CardContent sx={{p:{xs:3,sm:5}}}><Stack alignItems="center" textAlign="center"><CheckCircleRounded color="success" sx={{fontSize:58}}/><Typography variant="h4" mt={2}>Import complete</Typography><Typography color="text.secondary" mt={1}>Your selected leads are now available in Lead Management. No outreach was sent.</Typography></Stack><Grid container spacing={2} mt={3}>{Object.entries(summary).filter(([key])=>key!=='public_key').map(([key,value])=><Grid size={{xs:6,md:3}} key={key}><Box sx={{p:2,bgcolor:'background.default',borderRadius:2,textAlign:'center'}}><Typography variant="h5">{value}</Typography><Typography color="text.secondary" variant="body2">{key.replaceAll('_',' ')}</Typography></Box></Grid>)}</Grid><Stack direction="row" justifyContent="center" spacing={1.5} mt={4}><Button onClick={reset}>Import another file</Button><Button component="a" href="/app/leads" variant="contained">View leads</Button></Stack></CardContent></Card>}
    <Typography variant="h5" mt={5} mb={2}>Import history</Typography><Box sx={{height:350,bgcolor:'white',borderRadius:3}}><DataGrid rows={history} columns={historyCols} getRowId={r=>r.public_key} disableRowSelectionOnClick slots={{noRowsOverlay:()=> <Box sx={{display:'grid',placeItems:'center',height:'100%',color:'text.secondary'}}>No imports completed yet.</Box>}}/></Box>
  </>;
}
