import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Button, Dialog, DialogActions, DialogContent, DialogTitle } from '@mui/material';
import { getLeads } from '../../services/leads';
import { getCampaign, saveCampaign, sendCampaign } from '../../services/campaigns';
import './CampaignWizard.css';

const steps = ['Choose source', 'Review leads', 'AI verification', 'Select template', 'Preview', 'Send'];
const templates = [
  { key: 'template1-initial-outreach', label: 'Initial Outreach' },
  { key: 'template2-first-follow-up', label: 'First Follow-Up' },
  { key: 'template3-hr-platform-demo', label: 'HR Platform Demo' },
  { key: 'template4-commonoffice-outreach', label: 'CommonOffice Outreach' },
  { key: 'template5-last-follow-up', label: 'Last Follow-Up' },
];

export default function CampaignWizard() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const reuseKey = searchParams.get('reuse');
  const [active, setActive] = useState(0);
  const [form, setForm] = useState({ source: '', selected: [], aiVerification: false, template: templates[0].key, subject: '', sending: false });
  const [leads, setLeads] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [leadSearch, setLeadSearch] = useState('');
  const [leadDialogOpen, setLeadDialogOpen] = useState(false);
  const loadLeads = () => { setLoading(true); setError(''); return getLeads({ page: 1, limit: 100 }).then(response => { const rows = Array.isArray(response.data) ? response.data : []; setLeads(rows); return rows; }).catch(requestError => { setError(requestError.response?.data?.message || 'Unable to load leads'); return []; }).finally(() => setLoading(false)); };
  useEffect(() => { if (form.source === 'DATABASE' && !leads.length) loadLeads(); }, [form.source]);
  useEffect(() => { if (!reuseKey) return; setLoading(true); getCampaign(reuseKey).then(result => { const campaign = result.data; setForm(current => ({ ...current, source: campaign.source || 'DATABASE', selected: Array.isArray(campaign.lead_keys) ? campaign.lead_keys : [], template: campaign.provider_template_id || '', subject: campaign.subject || '' })); setActive(1); setLeadDialogOpen(true); setNotice('Campaign copied. Review the recipients, then select a template and send again.'); }).catch(requestError => setError(requestError.response?.data?.message || 'Unable to reuse campaign')).finally(() => setLoading(false)); }, [reuseKey]);
  const selectedLeads = useMemo(() => leads.filter(lead => form.selected.includes(lead.public_key)), [leads, form.selected]);
  const filteredLeads = useMemo(() => { const term = leadSearch.trim().toLowerCase(); if (!term) return leads; return leads.filter(lead => [lead.name, lead.first_name, lead.last_name, lead.company, lead.email, lead.job_title].some(value => String(value || '').toLowerCase().includes(term))); }, [leads, leadSearch]);
  const allVisibleSelected = filteredLeads.length > 0 && filteredLeads.every(lead => form.selected.includes(lead.public_key));
  const toggleVisible = checked => update('selected', checked ? [...new Set([...form.selected, ...filteredLeads.map(lead => lead.public_key)])] : form.selected.filter(key => !filteredLeads.some(lead => lead.public_key === key)));
  const selectedTemplate = templates.find(item => item.key === form.template);
  const uniqueCompanies = useMemo(() => new Set(selectedLeads.map(lead => String(lead.company || '').trim().toLowerCase()).filter(Boolean)).size, [selectedLeads]);
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const toggleLead = key => update('selected', form.selected.includes(key) ? form.selected.filter(item => item !== key) : [...form.selected, key]);
  const validate = () => { setError(''); if (active === 0 && !form.source) return setError('Choose a lead source before continuing'), false; if (active === 1 && form.source === 'DATABASE' && !form.selected.length) return setError('Select at least one lead'), false; if (active === 3 && !form.template) return setError('Select an email template'), false; return true; };
  const next = () => { if (validate()) setActive(value => Math.min(value + 1, steps.length - 1)); };
  const campaignPayload = () => ({ source: form.source || 'DATABASE', lead_keys: form.selected, template_key: null, template_name: selectedTemplate?.label || form.template || null, provider_template_id: form.template || null, subject: form.subject || null, status: 'DRAFT' });
  const saveDraft = async () => { try { await saveCampaign(campaignPayload()); navigate('/app/campaigns'); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to save campaign'); } };
  const sendNow = async () => { setError(''); update('sending', true); try { const saved = await saveCampaign(campaignPayload()); const result = await sendCampaign(saved.data.public_key, true); if(result.success===false||result.data?.failed){const detail=result.data?.results?.find(item=>item.status==='FAILED')?.message;throw new Error(detail||result.message||'Campaign failed to send')} setNotice(result.data.sent + ' emails sent'); setTimeout(() => navigate('/app/campaigns'), 1200); } catch (requestError) { setError(requestError.response?.data?.message || requestError.message || 'Unable to send campaign'); update('sending', false); } };

  return <div className="campaign-page"><header><div><p className="page-kicker">Campaigns</p><h1>Create campaign</h1><p>Choose leads, select a Resend template, preview, and send.</p></div><Link to="/app/campaigns" className="quiet-link">Cancel</Link></header><nav className="campaign-steps" aria-label="Campaign progress">{steps.map((label, index) => <button type="button" key={label} className={index === active ? 'active' : index < active ? 'complete' : ''} onClick={() => index <= active && setActive(index)}><span>{index < active ? '✓' : index + 1}</span><small>{label}</small></button>)}</nav>{error && <div className="wizard-error">{error}</div>}{notice && <div className="wizard-notice top-notice">{notice}</div>}<section className="wizard-card">
    {active === 0 && <><h2>Choose your lead source</h2><p>Select where campaign recipients should come from.</p><div className="source-grid"><button type="button" onClick={() => { update('source', 'DATABASE'); setActive(1); setLeadDialogOpen(true); }} className={'source-option ' + (form.source === 'DATABASE' ? 'selected' : '')}><strong>All leads</strong><span>Open and select saved leads from your database</span></button><Link to="/app/imports" className="source-option"><strong>Upload a file</strong><span>Import CSV or Excel, then return here</span></Link><button className="source-option disabled" disabled><strong>Apollo</strong><span>Configure Apollo to enable</span></button></div></>}
    {active === 1 && <><h2>Review leads</h2><p>Confirm the audience selected for this campaign.</p><div className="review-summary"><article><span>Selected leads</span><strong>{form.selected.length}</strong><small>Subscribed recipients</small></article><article><span>Unique companies</span><strong>{uniqueCompanies}</strong><small>Organizations represented</small></article></div><button type="button" className="wizard-secondary open-lead-dialog" onClick={() => setLeadDialogOpen(true)}>Change selected leads</button></>}
    {active === 2 && <><h2>AI verification <em>Optional</em></h2><p>You can verify company fit and contact relevance with AI, or skip this step and continue.</p><div className="ai-skip-card"><strong>Continue without AI verification</strong><span>No AI processing will run. Your selected leads remain unchanged.</span></div></>}
        {active === 3 && <><h2>Select a Resend template</h2><p>Each email receives the lead's <code>name</code> and <code>company_name</code>.</p><div className="template-list">{templates.map(template => <button key={template.key} onClick={() => update('template', template.key)} className={form.template === template.key ? 'selected' : ''}><strong>{template.label}</strong><span>{template.key}</span></button>)}</div></>}
    {active === 4 && <><h2>Preview campaign</h2><p>Review your campaign settings before final confirmation.</p><dl className="campaign-summary"><div><dt>Recipients</dt><dd>{selectedLeads.length}</dd></div><div><dt>Template</dt><dd>{selectedTemplate?.label || form.template}</dd></div><div><dt>Lead source</dt><dd>{form.source || '—'}</dd></div><div><dt>AI verification</dt><dd>Skipped</dd></div></dl></>}
    {active === 5 && <><h2>Final confirmation</h2><p>Review everything carefully. Sending requires an enabled Resend connection.</p><dl className="campaign-summary"><div><dt>Lead source</dt><dd>{form.source || '—'}</dd></div><div><dt>Recipients</dt><dd>{selectedLeads.length}</dd></div><div><dt>Template</dt><dd>{selectedTemplate?.label || '—'}</dd></div><div><dt>Variables</dt><dd>Lead name + company</dd></div></dl></>}
    <footer><button className="wizard-secondary" disabled={active === 0} onClick={() => setActive(value => value - 1)}>Back</button><div className="footer-actions"><button className="wizard-secondary" onClick={saveDraft}>Save draft</button>{active < steps.length - 1 ? <button className="wizard-primary" onClick={next}>{active === 2 ? 'Skip & continue' : 'Continue'}</button> : <button className="wizard-primary" disabled={form.sending} onClick={sendNow}>{form.sending ? 'Sending...' : 'Send campaign'}</button>}</div></footer>
  </section><Dialog open={leadDialogOpen} onClose={() => setLeadDialogOpen(false)} fullWidth maxWidth="lg" PaperProps={{sx:{borderRadius:3}}}><DialogTitle>Select campaign leads</DialogTitle><DialogContent><p className="dialog-help">Search and select the subscribed leads that should receive this campaign.</p><div className="lead-search dialog-search"><input type="search" value={leadSearch} onChange={event => setLeadSearch(event.target.value)} placeholder="Search by name, company, email, or job title…" aria-label="Search campaign leads"/><span>{filteredLeads.length} result{filteredLeads.length === 1 ? '' : 's'} · {form.selected.length} selected</span></div>{loading ? <div className="wizard-empty">Loading leads...</div> : leads.length === 0 ? <div className="wizard-empty">No leads available. Import leads first.</div> : filteredLeads.length === 0 ? <div className="wizard-empty compact">No leads match your search.</div> : <div className="lead-picker dialog-lead-picker"><label className="lead-picker-head"><input type="checkbox" checked={allVisibleSelected} onChange={event => toggleVisible(event.target.checked)}/><span>Lead</span><span>Company</span><span>Email</span></label>{filteredLeads.map(lead => <label key={lead.public_key}><input type="checkbox" checked={form.selected.includes(lead.public_key)} onChange={() => toggleLead(lead.public_key)}/><span>{lead.name || 'Unnamed lead'}</span><span>{lead.company || '—'}</span><span>{lead.email}</span></label>)}</div>}</DialogContent><DialogActions sx={{px:3,pb:2.5}}><Button onClick={() => setLeadDialogOpen(false)}>Cancel</Button><Button variant="contained" disabled={!form.selected.length} onClick={() => { setLeadDialogOpen(false); setActive(2); }}>Use {form.selected.length || ''} selected lead{form.selected.length === 1 ? '' : 's'}</Button></DialogActions></Dialog></div>;
}
